/** Curated starter set loaded on first paint for a fast, impressive landing. */
export const FEATURED: string[] = [
  "openai",
  "anthropic",
  "stripe",
  "databricks",
  "vercel",
  "linear",
  "cursor",
  "notion",
  "perplexity",
  "xai",
  "nvidia",
  "apple",
  "palantir",
  "cloudflare",
  "figma",
  "roblox",
];

export interface StarterPack {
  id: string;
  label: string;
  slugs: string[];
}

/**
 * Quick-add company bundles by industry, shown on onboarding and in the
 * toolbar so users don't have to hand-search the 8.5k-company registry.
 *
 * Every slug here was resolved against the live registry (sites.ts) by
 * exact company name match, not guessed — a name that doesn't appear in
 * this registry (not every company uses Ashby/Greenhouse/Lever/Workday/
 * SmartRecruiters) is simply absent from its pack rather than mismatched
 * to an unrelated company that happens to share a short name.
 */
export const STARTER_PACKS: StarterPack[] = [
  { id: "popular", label: "Popular picks", slugs: FEATURED },
  {
    id: "ai-ml",
    label: "AI & ML",
    slugs: [
      "openai",
      "anthropic",
      "xai",
      "cohere",
      "mistral",
      "perplexity",
      "scaleai",
      "databricks",
      "runway",
      "character",
      "inflectionai",
      "togetherai",
      "fireworks",
      "anyscale",
      "langchain",
      "pinecone",
      "cerebras",
      "assembly",
      "elevenlabs",
      "deepgram",
      "baseten",
      "modal",
      "gleanwork",
      "harvey",
      "cursor",
      "synthesia",
      "speak",
      "suno",
      "lumaai",
      "worldlabs",
      "physicalintelligence",
      "imbue",
      "decagon",
      "sierra",
      "vercel",
      "exa",
    ],
  },
  {
    id: "fintech",
    label: "Fintech & Payments",
    slugs: [
      "stripe",
      "coinbase",
      "robinhood",
      "plaid",
      "chime",
      "affirm",
      "ramp",
      "block",
      "wise",
      "brex",
      "mercury",
      "marqeta",
      "wealthfront",
      "betterment",
      "sofi",
      "current",
      "gusto",
      "remotecom",
      "carta",
      "angellist",
      "addepar1",
      "airwallex",
      "moderntreasury",
      "melio",
      "highnote",
      "unit",
      "column",
      "alloy",
      "persona",
      "sardine",
      "capchase",
      "parafin",
      "kikoff",
      "moonpay",
    ],
  },
  {
    id: "crypto-web3",
    label: "Crypto & Web3",
    slugs: [
      "coinbase",
      "chainalysis-careers",
      "alchemy",
      "opensea",
      "uniswap",
      "consensys",
      "anchorage",
      "gemini",
      "fireblocks",
      "paxos",
      "ripple",
      "polygon-labs",
      "blockdaemon",
      "trm-labs",
      "figment",
      "blockworks",
      "moonpay",
      "bitgo",
      "zerion",
      "phantom",
    ],
  },
  {
    id: "devtools-infra",
    label: "Dev Tools & Infra",
    slugs: [
      "gitlab",
      "mongodb",
      "datadog",
      "elastic",
      "supabase",
      "netlify",
      "docker",
      "circleci",
      "vercel",
      "planetscale",
      "confluent",
      "redis",
      "grafanalabs",
      "sentry",
      "pagerduty",
      "newrelic",
      "jfrog",
      "postman",
      "cloudflare",
      "fastly",
      "render",
      "railway",
      "temporal",
      "n8n",
      "zapier",
      "snowflake",
      "clickhouse",
      "neon",
      "workos",
      "okta",
      "1password",
      "launchdarkly",
      "honeycomb",
      "vanta",
      "drata",
      "warp",
      "replit",
      "gitbook",
      "linear",
    ],
  },
  {
    id: "cybersecurity",
    label: "Cybersecurity",
    slugs: [
      "crowdstrike",
      "okta",
      "1password",
      "vanta",
      "drata",
      "tanium",
      "netskope",
      "zscaler",
      "cloudflare",
      "datadog",
      "knowbe4",
      "huntress",
      "chainguard",
      "semgrep",
      "socket",
      "materialsecurity",
    ],
  },
  {
    id: "enterprise-saas",
    label: "Enterprise SaaS",
    slugs: [
      "salesforce",
      "adobe",
      "uber",
      "airbnb",
      "workday",
      "servicenow",
      "zoom",
      "asana",
      "notion",
      "airtable",
      "figma",
      "Canva",
      "boxinc",
      "dropbox",
      "smartsheet",
      "freshworks",
      "hubspotjobs",
      "intercom",
      "frontcareers",
      "gongio",
      "outreach",
      "salesloft",
      "chilipiper",
      "calendly",
    ],
  },
  {
    id: "gaming-media",
    label: "Gaming & Media",
    slugs: [
      "riotgames",
      "epicgames",
      "discord",
      "twitch",
      "spotify",
      "roblox",
      "scopely",
      "zyngacareers",
      "voodoo",
      "jamcity",
      "applovin",
      "bungie",
      "taketwo",
      "Ubisoft2",
      "bhvr",
    ],
  },
  {
    id: "social-consumer",
    label: "Social & Consumer",
    slugs: [
      "discord",
      "pinterest",
      "reddit",
      "bumbleinc",
      "cameo",
      "nextdoor",
      "patreon",
      "substack",
      "twitch",
      "spotify",
      "duolingo",
      "strava",
      "hs",
      "calm",
      "airbnb",
    ],
  },
  {
    id: "ecommerce-retail",
    label: "E-commerce & Retail",
    slugs: [
      "instacart",
      "wayfair",
      "faire",
      "stockx",
      "poshmark",
      "klaviyo",
      "attentive",
      "postscript",
      "recharge",
      "route",
      "narvar",
      "yotpo",
      "gorgias",
    ],
  },
  {
    id: "delivery-logistics",
    label: "Delivery & Logistics",
    slugs: [
      "instacart",
      "uber",
      "lyft",
      "gopuff",
      "deliveroo",
      "Grab",
      "bringg",
      "project44",
      "fourkites",
      "samsara",
      "motive",
      "loadsmart",
      "nuro",
      "waabi",
      "applied",
    ],
  },
  {
    id: "healthcare-biotech",
    label: "Healthcare & Biotech",
    slugs: [
      "ro",
      "hims-and-hers",
      "oscar",
      "cedar",
      "includedhealth",
      "forward",
      "benchling",
      "insitro",
      "ginkgobioworks",
      "grailbio",
      "freenome",
      "truveta",
      "doximity",
      "headway",
      "springhealth66",
      "lyrahealth",
      "modernhealth",
      "mavenclinic",
      "khealthcareers",
    ],
  },
  {
    id: "hardware-robotics",
    label: "Hardware & Robotics",
    slugs: [
      "andurilindustries",
      "figureai",
      "physicalintelligence",
      "skydio",
      "flyzipline",
      "waymo",
      "nvidia",
      "samsara",
      "nuro",
      "apple",
      "agilityrobotics",
      "diligentrobotics",
      "brightmachines",
      "shieldai",
    ],
  },
  {
    id: "aerospace-defense",
    label: "Aerospace & Defense",
    slugs: [
      "spacex",
      "andurilindustries",
      "relativity",
      "astranis",
      "vardaspace",
      "shieldai",
      "palantir",
      "applied",
      "skydio",
    ],
  },
  {
    id: "automotive-ev",
    label: "Automotive & EV",
    slugs: [
      "lucidmotors",
      "waymo",
      "zoox",
      "nuro",
      "chargepoint",
      "motional",
      "applied",
    ],
  },
  {
    id: "climate-energy",
    label: "Climate & Energy",
    slugs: [
      "chargepoint",
      "formenergy",
      "redwoodmaterials",
      "cfsenergy",
      "aurorasolar",
      "watershed",
      "patch",
      "charmindustrial",
      "antora",
      "base-power",
    ],
  },
  {
    id: "edtech",
    label: "EdTech",
    slugs: [
      "duolingo",
      "coursera",
      "udemy",
      "khanacademy",
      "masterclass",
      "outschool",
      "multiverse",
      "handshake",
      "datacamp",
      "developintelligence",
    ],
  },
  {
    id: "recruiting-hr",
    label: "HR & Recruiting",
    slugs: [
      "gusto",
      "remotecom",
      "lattice",
      "cultureamp",
      "greenhouse",
      "ashby",
      "handshake",
      "multiverse",
      "justworks",
    ],
  },
];
